name: ci
on: push

env:
  GHIDRA_VERSION: "11.0"
  GHIDRA_BUILD_DATE: 20231222
  GHIDRA_SHA256: f1f240f91cf6b1dffc9a4148384ee3c6b269a8ae27c6f981577973e00043ad94
  GHIDRA_INSTALL_DIR: /home/runner/ghidra

jobs:
  build_and_test:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Ghidra
        run: .github/scripts/install_ghidra.sh

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build extension
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: build/distributions/*_ghidra-gotools.zip
          if-no-files-found: 'error'
  release:
    if: github.ref_type == 'tag'
    name: Create draft release
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: distribution
      - name: Create release and upload distribution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --verify-tag --generate-notes --draft "${{ github.ref_name }}"
          gh release upload "${{ github.ref_name }}" *_ghidra-gotools.zip